import { Category, CategoryId, Badge, PaperclipStage } from '../types';

// NOT: Bu liste artık canlı Supabase `categories` tablosuyla birebir
// eşleşiyor (id = DB slug, name = Türkçe görünen isim). Detaylar için
// src/types/index.ts'teki CategoryId açıklamasına bakın.
export const CATEGORIES: Category[] = [
  {
    id: 'electronics',
    name: 'Elektronik',
    iconName: 'Laptop',
    color: '#059669', // emerald
    itemCount: 428,
    avgCo2Savings: 14.5,
    avgWaterSavings: 380,
  },
  {
    id: 'sports',
    name: 'Spor & Outdoor',
    iconName: 'Bike',
    color: '#d97706', // amber
    itemCount: 312,
    avgCo2Savings: 9.8,
    avgWaterSavings: 240,
  },
  {
    id: 'home-living',
    name: 'Ev & Yaşam',
    iconName: 'Home',
    color: '#047857',
    itemCount: 520,
    avgCo2Savings: 7.2,
    avgWaterSavings: 190,
  },
  {
    id: 'fashion',
    name: 'Giyim & Moda',
    iconName: 'Shirt',
    color: '#b45309',
    itemCount: 684,
    avgCo2Savings: 6.4,
    avgWaterSavings: 850,
  },
  {
    id: 'hobby',
    name: 'Hobi & Oyun',
    iconName: 'Gamepad2',
    color: '#10b981',
    itemCount: 260,
    avgCo2Savings: 4.8,
    avgWaterSavings: 120,
  },
  {
    id: 'books',
    name: 'Kitap',
    iconName: 'BookOpen',
    color: '#059669',
    itemCount: 260,
    avgCo2Savings: 3.1,
    avgWaterSavings: 95,
  },
  {
    id: 'music',
    name: 'Müzik',
    iconName: 'Music',
    color: '#0d9488',
    itemCount: 135,
    avgCo2Savings: 3.6,
    avgWaterSavings: 80,
  },
  {
    id: 'photography',
    name: 'Fotoğraf',
    iconName: 'Camera',
    color: '#7c3aed',
    itemCount: 98,
    avgCo2Savings: 12.1,
    avgWaterSavings: 260,
  },
  {
    id: 'collectibles',
    name: 'Koleksiyon',
    iconName: 'Sparkles',
    color: '#db2777',
    itemCount: 121,
    avgCo2Savings: 4.2,
    avgWaterSavings: 110,
  },
  {
    id: 'other',
    name: 'Diğer',
    iconName: 'Package',
    color: '#78716c',
    itemCount: 96,
    avgCo2Savings: 5.0,
    avgWaterSavings: 150,
  },
];

export const SAFE_MEETING_POINTS = [
  {
    id: 'smp-1',
    city: 'İstanbul',
    district: 'Kadıköy',
    name: 'Kadıköy İskelesi Güvenli Takas Alanı',
    address: 'Kadıköy Rıhtım Meydanı Zabıta Yanı, İstanbul',
    hasCamera: true,
    hasSecurity: true,
    hours: '08:00 - 22:00',
    lat: 40.9904,
    lng: 29.0254,
  },
  {
    id: 'smp-2',
    city: 'İstanbul',
    district: 'Beşiktaş',
    name: 'Beşiktaş Meydan Takas Noktası',
    address: 'Beşiktaş İskelesi Önü Güvenli Toplanma Noktası, İstanbul',
    hasCamera: true,
    hasSecurity: true,
    hours: '08:00 - 23:00',
    lat: 41.0422,
    lng: 29.0067,
  },
  {
    id: 'smp-3',
    city: 'İstanbul',
    district: 'Şişli',
    name: 'Cevahir AVM Girişi Danışma Yanı',
    address: 'Büyükdere Cad. No:22 Şişli, İstanbul',
    hasCamera: true,
    hasSecurity: true,
    hours: '10:00 - 22:00',
    lat: 41.0632,
    lng: 28.9930,
  },
  {
    id: 'smp-4',
    city: 'Ankara',
    district: 'Çankaya',
    name: 'Kızılay Metro Çıkışı Güvenli Nokta',
    address: 'Kızılay Meydanı Güven Park Yanı, Ankara',
    hasCamera: true,
    hasSecurity: true,
    hours: '08:00 - 21:00',
    lat: 39.9208,
    lng: 32.8541,
  },
  {
    id: 'smp-5',
    city: 'İzmir',
    district: 'Konak',
    name: 'Alsancak İskelesi Takas İstasyonu',
    address: 'Alsancak Vapur İskelesi Girişi, İzmir',
    hasCamera: true,
    hasSecurity: true,
    hours: '08:00 - 22:00',
    lat: 38.4382,
    lng: 27.1413,
  },
];

export const INITIAL_BADGES: Badge[] = [
  {
    id: 'b-1',
    title: 'İlk Takasım',
    description: 'İlk başarılı takasını başarıyla tamamladın.',
    iconName: 'Repeat',
    category: 'trade',
    isEarned: true,
    earnedDate: '12 Nisan 2024',
    progressPercent: 100,
    maxProgress: 1,
    currentProgress: 1,
  },
  {
    id: 'b-2',
    title: 'Güvenilir Üye',
    description: "Trust Score'un 4.50 barajını aştı ve 5 onaylı takas yaptın.",
    iconName: 'ShieldCheck',
    category: 'trust',
    isEarned: true,
    earnedDate: '28 Nisan 2024',
    progressPercent: 100,
    maxProgress: 5,
    currentProgress: 5,
  },
  {
    id: 'b-3',
    title: 'Çevre Dostu',
    description: '50 kg CO₂e emisyonunun önlenmesine katkı sağladın.',
    iconName: 'Leaf',
    category: 'eco',
    isEarned: true,
    earnedDate: '8 Mayıs 2024',
    progressPercent: 100,
    maxProgress: 50,
    currentProgress: 127.4,
  },
  {
    id: 'b-4',
    title: 'Loop Pioneer',
    description: 'En az 3 kişilik çoklu bir döngüsel takasa (Loop) katıldın.',
    iconName: 'Share2',
    category: 'community',
    isEarned: true,
    earnedDate: '14 Mayıs 2024',
    progressPercent: 100,
    maxProgress: 1,
    currentProgress: 1,
  },
  {
    id: 'b-5',
    title: 'Takas Ustası',
    description: '10 başarılı takas tamamlayarak toplulukta ustalığa eriştin.',
    iconName: 'Award',
    category: 'trade',
    isEarned: false,
    progressPercent: 70,
    maxProgress: 10,
    currentProgress: 7,
  },
  {
    id: 'b-6',
    title: 'Hızlı Yanıt',
    description: 'Gelen tekliflere ortalama 15 dakika altında dönüş sağladın.',
    iconName: 'Zap',
    category: 'trust',
    isEarned: true,
    earnedDate: '2 Mayıs 2024',
    progressPercent: 100,
    maxProgress: 15,
    currentProgress: 12,
  },
  {
    id: 'b-7',
    title: 'Topluluk Elçisi',
    description: 'Topluluk hikayesi paylaştın veya bir etkinliğe katıldın.',
    iconName: 'Users',
    category: 'community',
    isEarned: true,
    earnedDate: '19 Mayıs 2024',
    progressPercent: 100,
    maxProgress: 1,
    currentProgress: 1,
  },
  {
    id: 'b-8',
    title: '50 Takas Efsanesi',
    description: '50 başarılı takasa ulaşarak sürdürülebilirlik kahramanı ol.',
    iconName: 'Crown',
    category: 'trade',
    isEarned: false,
    progressPercent: 14,
    maxProgress: 50,
    currentProgress: 7,
  },
];

export const PAPERCLIP_STAGES: PaperclipStage[] = [
  {
    stageNumber: 1,
    itemTitle: 'Kırmızı Ataç',
    category: 'Kırtasiye',
    image: 'https://images.unsplash.com/photo-1585336261026-7f12384a28bb?w=400&auto=format&fit=crop&q=80',
    estimatedImpact: 0.05,
    dateCompleted: '10 Mart 2024',
    isCompleted: true,
    isCurrent: false,
  },
  {
    stageNumber: 2,
    itemTitle: 'Vintage Dolma Kalem',
    category: 'Kırtasiye',
    image: 'https://images.unsplash.com/photo-1583485088034-697b5bc54ccd?w=400&auto=format&fit=crop&q=80',
    estimatedImpact: 0.4,
    dateCompleted: '22 Mart 2024',
    isCompleted: true,
    isCurrent: false,
  },
  {
    stageNumber: 3,
    itemTitle: 'Dune Klasik Ciltli Kitap',
    category: 'Kitap',
    image: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=400&auto=format&fit=crop&q=80',
    estimatedImpact: 1.8,
    dateCompleted: '8 Nisan 2024',
    isCompleted: true,
    isCurrent: false,
  },
  {
    stageNumber: 4,
    itemTitle: 'Kablosuz ANC Kulaklık',
    category: 'Elektronik',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&auto=format&fit=crop&q=80',
    estimatedImpact: 5.2,
    dateCompleted: '25 Nisan 2024',
    isCompleted: true,
    isCurrent: false,
  },
  {
    stageNumber: 5,
    itemTitle: 'Canon DSLR Fotoğraf Makinesi',
    category: 'Elektronik',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?w=400&auto=format&fit=crop&q=80',
    estimatedImpact: 8.6,
    isCompleted: false,
    isCurrent: true,
  },
  {
    stageNumber: 6,
    itemTitle: 'Bianchi Şehir Bisikleti',
    category: 'Spor',
    image: 'https://images.unsplash.com/photo-1485965120184-e220f721d03e?w=400&auto=format&fit=crop&q=80',
    estimatedImpact: 14.2,
    isCompleted: false,
    isCurrent: false,
  },
  {
    stageNumber: 7,
    itemTitle: 'MacBook Air Dizüstü Bilgisayar',
    category: 'Elektronik',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=400&auto=format&fit=crop&q=80',
    estimatedImpact: 22.0,
    isCompleted: false,
    isCurrent: false,
  },
];
